# global:
#   configValidation: false

ingress:
  enabled: true

grafana:
  enabled: true

kiali:
  enabled: true
  dashboard:
    username: admin
    passphrase: admin

tracing:
  enabled: true

servicegraph:
  enabled: true
